---
web:
  build: .
  container_name: "${VIRTUAL_HOST}"
  environment:
    - "LETSENCRYPT_EMAIL=${EMAIL}"
    - "LETSENCRYPT_HOST=${VIRTUAL_HOST}"
    - "VIRTUAL_HOST=${VIRTUAL_HOST}"
  expose:
    - "80"
  network_mode: bridge
  restart: always
  volumes:
    - "./web:/usr/share/nginx/html"
